name: open_container
description: A new Flutter project. Created by Slidy

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  # animations: ^1.1.2
  animations: 
    git:
      url: git://github.com/danielgorka/packages.git
      path: packages/animations
  dio: ^3.0.10
  rxdart: ^0.25.0
  flutter_modular: ^2.0.1
  flutter:
    sdk: flutter

# dependency_overrides:
#   animations: 
#     git:
#       url: git://github.com/danielgorka/packages.git
#       path: packages/animations
dev_dependencies:
  mockito: ^4.1.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
